export default {
  'FooterHK.cmsLink': '/en-hk',
  'FooterHK.cfsLink': '/hk/en',
  'FooterHK.titleAboutJobsDB': 'About JobsDB',
  'FooterHK.titleJobSeeker': 'Job Seekers',
  'FooterHK.titleEmployer': 'Employers',
  'FooterHK.titleConnect': 'Connect',
  'FooterHK.copyright': '© jobsDB. All Rights Reserved',
  'FooterHK.siteMapLink': '/sitemap',
  'FooterHK.siteMapLinkText': 'Site Map',
  'FooterHK.termsLink': '/pages/terms/terms-conditions',
  'FooterHK.termsLinkText': 'Terms & Conditions',
  'FooterHK.privacyLink': '/pages/terms/privacy-policy',
  'FooterHK.privacyLinkText': 'Privacy Statement',
  'FooterHK.aboutJobsDB': 'About jobsDB',
  'FooterHK.aboutJobsDBLink': '/pages/aboutus',
  'FooterHK.faq': 'FAQ',
  'FooterHK.faqLink': '/StaticContentFullContainer/AboutUS/faq/index.htm',
  'FooterHK.career': 'Career @ jobsDB',
  'FooterHK.careerLink': '/Search/FindJobs?JSRV=1&AccNums=1&SubAccount=14',
  'FooterHK.contactUs': 'Contact us',
  'FooterHK.contactUsLink': '/pages/regional-coverage',
  'FooterHK.partners': 'International partners',
  'FooterHK.browseJobs': 'Browse jobs',
  'FooterHK.browseJobsLink': '/browse',
  'FooterHK.resumes': 'Post resumes',
  'FooterHK.resumesLink': '/Resumes/ResumeIndex',
  'FooterHK.jobAlerts': 'Job Alerts',
  'FooterHK.jobAlertsLink': '/JobAlert/JobAlertCreation',
  'FooterHK.careerInsights': 'Career Insights',
  'FooterHK.postJob': 'Post a job',
  'FooterHK.postJobLink': '/cms/employer/product-services/job-ads/',
  'FooterHK.searchCandidates': 'Search candidates',
  'FooterHK.searchCandidatesLink': '/cms/employer/product-services/talent-search/',
  'FooterHK.advertise': 'Advertise with us',
  'FooterHK.advertiseLink': '/cms/employer/product-and-services/',
  'FooterHK.myJobsDBTitle': 'My jobsDB',
  'FooterHK.myJobsDBUrl': '/MyJobsDB',
  'FooterHK.careerInsightsTitle': 'Career Insights',
  'FooterHK.careerInsightsUrl': '/career-insights',
  'FooterHK.bestCompanies': 'Best Companies',
  'FooterHK.bestCompaniesLink': '/companies',
  'FooterHK.facebook': 'Facebook',
  'FooterHK.facebookLink': 'https://www.facebook.com/JobsDB.HongKong',
  'FooterHK.twitter': 'Twitter',
  'FooterHK.twitterLink': 'https://twitter.com/HKJobs',
  'FooterHK.appStore': 'jobsDB @ App Store',
  'FooterHK.appStoreLink': 'https://itunes.apple.com/hk/app/jobsdb-job-search/id414607432',
  'FooterHK.googlePlay': 'jobsDB @ Google Play',
  'FooterHK.googlePlayLink': 'https://play.google.com/store/apps/details?id=com.jobsdb',
  'FooterHK.BabaJobLink': 'http://www.babajob.com/',
  'FooterHK.BdjobsLink': 'http://www.bdjobs.com/',
  'FooterHK.BrighterMondayLink': 'http://www.brightermonday.com/',
  'FooterHK.CathoLink': 'http://www.catho.com.br/',
  'FooterHK.JobbermanLink': 'http://www.jobberman.com/',
  'FooterHK.JobStreetLink': 'http://www.jobstreet.com/',
  'FooterHK.JoraLink': 'https://hk.jora.com/',
  'FooterHK.ManagerLink': 'http://www.manager.com.br/',
  'FooterHK.OCCLink': 'https://www.occ.com.mx/',
  'FooterHK.SeamanJobsiteLink': 'http://www.seamanjobsite.com/',
  'FooterHK.SEEKLink': 'http://www.seek.com.au/',
  'FooterHK.WorkAbroadLink': 'http://www.workabroad.ph/',
  'FooterHK.WorkanaLink': 'https://www.workana.com/',
  'FooterHK.ZhaopinLink': 'http://www.zhaopin.com/'
};
